---
- name: Ansible app server setup playbook
  gather_facts: false
  hosts: _AppServer
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "/home/etokral/.ssh/id_rsa.pub"
  tasks:
    - name: Inatall package
      yum:
        name: httpd
        state: present
      become: true
    - name: start and enable service
      systemd:
        name: httpd
        state: started
        enabled: yes
      become: true
    - name: Install pip module
      pip:
        executable: pip3
        name: psycopg2-binary
        state: present
      become: true
    - name: Copy cgi config files 
      copy:
        src: /home/etokral/Technology/Terraform/my-terraform-tests/ansible/files/cgi.conf
        dest: /etc/httpd/conf.d
      become: true
    - name: Copy python files 
      copy:
        src: /home/etokral/Technology/Terraform/my-terraform-tests/ansible/files/hostDate.py
        dest: /var/www/cgi-bin
        mode: '755'
      become: true
    - name: Copy ini files 
      copy:
        src: /home/etokral/Technology/Terraform/my-terraform-tests/ansible/files/database.ini
        dest: /var/www/cgi-bin
        mode: '755'
      become: true
    - name: Copy connect files 
      copy:
        src: /home/etokral/Technology/Terraform/my-terraform-tests/ansible/files/connectToDb.py
        dest: /var/www/cgi-bin
        mode: '755'
      become: true
