---
- name: Ansible app server setup playbook
  gather_facts: false
  hosts: _DbServer
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "/home/etokral/.ssh/id_rsa.pub"
  tasks:
    - name: Inatall postgres packages
      yum:
        name: "{{ packages }}"
        state: present 
      vars:
        packages:
        - postgresql
        - postgresql-server
      become: true
    - name: Install pip module
      pip:
        executable: pip3
        name: psycopg2-binary
        state: present
      become: true
    - name: Check if postgres is initialized
      ansible.builtin.stat:
        path: /var/lib/pgsql/data/pg_hba.conf
      register: postgres_data
      become: true
    - name: Initialize postgres
      shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists
      become: true
    - name: Start and enable postgres service
      systemd:
        name: postgresql
        state: started
        enabled: yes
      become: true
