---
- name: Ansible files Playbook
  gather_facts: false
  hosts: _AppServer
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "/home/etokral/.ssh/id_rsa.pub"
  tasks:
    - name: Copy cgi config files 
      copy:
        src: /home/etokral/Technology/Terraform/my-terraform-tests/python/cgi.conf
        dest: /etc/httpd/conf.d
      become: true
    - name: Copy python files 
      copy:
        src: /home/etokral/Technology/Terraform/my-terraform-tests/python/hostDate.py
        dest: /var/www/cgi-bin
        mode: '755'
      become: true
