---
- name: Ansible Test Playbook
  gather_facts: false
  hosts: _AppServer
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "/home/etokral/.ssh/id_rsa.pub"
  tasks:
    - name: Run Shell Command
      command: echo "Hello World"
